---
modulesearchpaths:
    - /usr/lib/calamares/modules
sequence:
    - show:
        - welcome
    - show:
        - locale
    - show:
        - keyboard
    - exec:
        - partition
    - exec:
        - users
    - exec:
        - netinstall
    - exec:
        - bootloader
    - exec:
        - shellprocess
    - show:
        - finished
branding: windos
prompt-install: false
